try passing in babel as final module arg. test breaks tho
```
  ● codegen › codegen comment export a function

    TypeError: /Users/mark/code/babel-plugin-codegen/src/__tests__/index.ts: Cannot add property 0, object is not extensible
        at Array.push (<anonymous>)

      1 | import path from 'path'
    > 2 | import pluginTester from 'babel-plugin-tester'
        | ^
      3 | import stripAnsi from 'strip-ansi'
      4 | import plugin from '../'
      5 |

      at addExternalDependency (node_modules/@babel/core/lib/config/helpers/config-api.js:60:26)
      at module (src/__tests__/index.ts:2:1)
      at getReplacement (src/helpers.ts:48:14)
      at asProgram (src/replace.ts:26:25)
      at PluginPass.Program (src/index.ts:25:11)
      at newFn (node_modules/@babel/traverse/lib/visitors.js:177:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:53:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:40:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:100:31)
```